
 # GUESS NUMBER(USER GUESS)

 # its a game where you guess a number generated by the computer


import random

def guess(x):

    random_number=random.randint(1,x)
    guess=0

    while guess!=random_number:
        guess=int(input(f"guess a number between 1 and {x}"))
        if guess<random_number:
            print(f"sorry,guess again {x} too low")
        elif guess>random_number:
            print(f"sorry,guess again {x} too high")

    print(f"you have guessed the number correct, it is {random_number}")

guess(15)

#GUESS_NUMBER(COMPUTER GUESS)

def computer_guess(x):

    low=1
    high=x
    feedback=' '

    while feedback!='c':
        if low!=high:
            guess=random.randint(low,high)
        else:
            guess=low

        feedback=input(f'Is {guess} too high (h), too low(l), or correct(c)')

        if feedback=='h':
            high=guess-1
        elif feedback=='l':
            low=guess+1

    print(f'the computer guessed correctly {guess} is the number')

computer_guess(100)
